# This configuration uses the kitchen-ec2 plugin
# https://github.com/test-kitchen/kitchen-ec2
#
# The following environmental variables are required:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_SSH_KEY_ID
# - AWS_SUBNET_ID
#
# Please make sure the default VPC security group
# for the given subnet id allows inbound SSH.
---
driver:
  name: ec2
  region: us-east-1
  instance_type: t2.micro # AWS Free Tier
  associate_public_ip: true
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  tags:
    created-by: 'test-kitchen'
    launched-by: <%= ENV['USER'] %>
    Name: 'test-kitchen mesos-cookbook <%= Time.now.strftime("%d/%m/%Y %H:%M") %>'

busser:
  sudo: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: amazon-2015.09.1
    run_list:
      - recipe[yum]
    driver:
      image_id: ami-60b6c60a
    transport:
      username: ec2-user
# https://cloud-images.ubuntu.com/locator/ec2/
  - name: ubuntu-15.04
    run_list:
      - recipe[apt]
      - recipe[curl]
    driver:
      image_id: ami-2a4d1a40
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[curl]
    driver:
      image_id: ami-5c207736
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[curl]
    driver:
      image_id: ami-4505522f
# https://wiki.debian.org/Cloud/AmazonEC2Image
  - name: debian-8.4
    run_list:
      - recipe[apt]
      - recipe[curl]
    driver:
      image_id: ami-c8bda8a2
# https://wiki.centos.org/Cloud/AWS
  - name: centos-7
    run_list:
      - recipe[yum]
    driver:
      image_id: ami-6d1c2007
  - name: centos-6
    run_list:
      - recipe[yum]
    driver:
      image_id: ami-1c221e76

suites:
- &default
  name: 0-28-0
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
- <<: *default
  name: 0-27-2
  attributes:
    mesos:
      version: 0.27.2
- <<: *default
  name: 0-26-0
  attributes:
    mesos:
      version: 0.26.0
