source "https://supermarket.chef.io"

metadata

cookbook 'docker', '~> 2.2.9'
cookbook 'apache_zookeeper', git: 'git://github.com/dcode/apache_zookeeper'
cookbook 'mesos', git: 'git://github.com/mdsol/mesos_cookbook'
cookbook 'marathon', git: 'git://github.com/mdsol/marathon_cookbook'

